# Generated by Django 5.0.6 on 2024-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/main/img', verbose_name='Image'),
        ),
    ]
