# Generated by Django 5.0.6 on 2024-08-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_content_alter_news_title_useraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useraction',
        ),
    ]
