# Generated by Django 5.0.6 on 2024-09-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_warehouse_stock'),
        ('qrcodes', '0007_item_alter_qrscan_item_warehouse_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse_stock',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Warehouse_stock',
        ),
    ]
